In [2]:
import numpy as np
from IPython.core.debugger import Tracer

In [5]:
my_array = [
    [1,2,3,4,5],
    [6,7,8,9,0],
    [11,12,13,14,15]
]
a = np.array(my_array)
print a
print a.shape
print type(a[0])

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]
(3, 5)
<type 'numpy.ndarray'>


In [7]:
my_weight = np.array([])
print my_weight.shape[0]

0


In [3]:
class NN(object):
    def __init__(self, nodes_in_layers):
        """
            The constructor for the neural network. 
            @Arguments: 
                nodes_in_layers: The list specifying the number of nodes in each layer. And the length of the
                                 list specifies the number of layers. 
        """
        self.num_layers = len(nodes_in_layers)
        self.nodes_in_layers = nodes_in_layers
        self.weight = np.array([])
        self.layers = None
        
    def feedforward(self, data_nobias):
        """
        """
        #from IPython.core.debugger import Tracer
        #Tracer()()
        
        #Adding bias to the data: 
        data = np.ones([data_nobias.shape[0], data_nobias.shape[1]+1])
        data[:,:-1] = data_nobias
        
        if self.weight.shape[0] == 0 and self.layers is None:
            self.weight = []
            self.layers = []
            n = data.shape[1]
            for i in xrange(0, len(self.nodes_in_layers)):
                w_temp = np.random.random((self.nodes_in_layers[i], n))
                #print "Appending weight vector: {}".format(w_temp.shape)
                self.weight.append(w_temp)
                n = self.nodes_in_layers[i]
                self.layers.append(Layer(self.nodes_in_layers[i], i, w_temp))
                
            temp_data = data 
            for i in self.layers: 
                #print "Calculating Activation, data shape: {}, weight shape: {}".format(data.shape, i.w.shape)
                temp_activation = i.compute_next(temp_data)
                temp_data = temp_activation
            
            return temp_activation   
        

In [5]:
#Testing the NN Class. 
mynet = NN([1,2,3,2,1])
data = np.random.random((10, 1))
test =  mynet.feedforward(data)

print test

[[ 0.67663653]
 [ 0.67663424]
 [ 0.67662512]
 [ 0.67663143]
 [ 0.67663724]
 [ 0.67664527]
 [ 0.67663901]
 [ 0.67664229]
 [ 0.67664499]
 [ 0.676627  ]]


In [4]:
class Layer(object):
    
    
    def __init__(self, num_nodes, layer_index, w):
        """
        """
        self.num_nodes = num_nodes
        self.layer_index = layer_index
        self.w = w
        
    def compute_next(self, data):
        """
            Returns the activation function output. 
        """
        #print "Layer index: {}, data shape: {}, weight shape:{}".format(self.layer_index, data.shape, self.w.shape)
        self.activation = self.sigmoid(data.dot(self.w.transpose()))
        #print "Activation shape: {}".format(self.activation.shape)
        return self.activation
    
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))